apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    group: msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
      tier: backend
  template:
    metadata:
      labels:
        app: backend-app
        tier: backend
    spec:
      containers:
      - name: backend-app
        image: fabric8/backend:1.0
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000