apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  labels:
    group: msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-node
        image: fabric8/hola-springboot:1.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: LoadBalancer